protected/models/UserAuthItem.php
<?php

class UserAuthItem extends RemarcModel
{
	public $excludeFromAudit	= true; 
	private $asOfDate;
	
	/**
	 * Returns the static model of the specified AR class.
	 * @return CActiveRecord the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'assignments';
	}

	public function primaryKey()
	{
	    return array('userid', 'itemname');
	}
	
	public function rules()
	{
		return array(
			//array(implode(', ', array_keys($this->viewAttributes)) . ', userid', 'safe'),
            array('itemname, username, bizrule, data, userid', 'safe' ),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
	    return array(
	    		'User'		=> array(self::BELONGS_TO, 'User',		'userid'),
		        'AuthItem'	=> array(self::BELONGS_TO, 'AuthItem',	'itemname'),
	    );
	}
	
	public function search()
	{
		if(isset($_REQUEST[$this->modelName])) $this->attributes=$_REQUEST[$this->modelName];

		$criteria = new CDbCriteria;
		$criteria->compare('"userid"', $this->userid);
		$criteria->compare('lower("itemname")', strtolower($this->itemname), true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'pagination'=>array('pageSize'=>20),
			'sort'=>array(
				'defaultOrder'=>array('code'=>false),
				'attributes'=>array(
					'*',
				),
			),
		));
	}
	
	public function getGridColumns() {
		return array(
			$this->gridColumnButtons,
			'User.username',
			'itemname',
		);
	}
	
	
	public function getDetailAttributes() {
		return array(
			//'username',
			//'itemname',
		);
	}
	
	public function getGridColumnButtons() {
		return array(
			'class'=>'TbButtonColumn',
			'buttons'=>array(
				'delete'=>array('url'=>'array("/$data->modelName/delete/", "id"=>$data->primaryKey);'),
			),
			'template'=>'{delete}',
		);
	}


	public function getUserAuthItemName()
	{
		return $this->UserAuthItem->name;
	}
	
	public function getUserId()
	{
		return $this->userid;
	}
		
	public function getUsername()
	{ 
		$userModel = User::model()->findByPk($this->userid);
		return isset($userModel) ? $userModel->username : $this->userid;
	}
	
	public function getRoleOptions()
	{
		$roleAuthItems = AuthItem::model()->findAll('type = :type and name != :admin', array('type'=>2, 'admin'=>'Admin'));
		$roles = array();
		foreach($roleAuthItems as $item)
			$roles[$item->name] = $item->name;
		if( User::model()->findByPk(Yii::app()->user->id)->isAdmin ) $roles['Admin'] = 'Admin';
		return $roles;
	}
	
	public function getModelName()		{ return 'UserAuthItem'; }
	public function getModelsName()		{ return 'UserAuthItems'; }

	public function getModelsLabel()	{ return 'User Roles'; }
	public function getModelLabel()		{ return 'User Role'; }
	
	public function getId()				{ return array('itemname'=>$this->itemname, 'userid'=>$this->userid); }
	public function getDefaultSort()	{ return array('name'=>'itemname','order'=>'ASC'); }

	public function updateDependentFields($key=array())
	{
		// return; // short circuit
		
		if($key)
		{
			//$foreignKey			= $this->getModelPrimaryKeyName($key['name']);
			$foreignKey			= self::model($key['name'])->primaryKeyName;
			//Yii::trace("key: " . print_r($key,1));
			if($key['name'] == 'User')
			{
				$this->userid	= $key['value'];
				//Yii::trace("userid: {$this->userid}");
			}
			
			//$form				= $this->form;
			//$form['username']->showOnly = true;
		}
	}

}

protected/views/auditLog/create.php
<?php echo '<h2>New ' . $model->tableName() . '</h2>'; ?>

<?php echo $this->renderPartial('/common/form', array(
	'model'=>$model,
	'update'=>false,
)); ?>

protected/views/auditLog/listPick.php
<?php echo $this->renderPartial('/common/listPick', array(
	#'model'=>$model,
)); ?>

protected/views/auditLog/search.php
<?php
$clientScript = Yii::app()->getClientScript();
$baseUrl = Yii::app()->baseUrl;

$clientScript->registerCoreScript('jquery');
//$clientScript->registerScriptFile($baseUrl.'/assets/82dbe2db/jquery.js');
$clientScript->registerScriptFile($baseUrl.'/assets/anytime/anytimec.js');
$clientScript->registerCssFile($baseUrl.'/assets/anytime/anytimec.css');
$clientScript->registerCssFile($baseUrl.'/assets/e27f5f8f/css/redmond/jquery-ui-1.7.1.custom.css');
?>
<script type="text/javascript">
$(document).ready(function()
{
	 $("#AuditLogSearchForm_to, #AuditLogSearchForm_from").AnyTime_picker(
	      {
	          format: "%Y-%m-%d %H:%i:%s",
	          askSecond: true,
	          theme: 'redmond'
	      }
	 )
	 .each( function( index, item ){ // add clear buttons to "from" and "to" fields
		 var field = $(item);
		 var fieldId = field.attr('id');
		 var clearId = 'clear' + fieldId;
		 field.after('<a href="#" id="' + clearId + '">Clear</a>' );
		 $("#" + clearId ).click( function(){$("#" + fieldId ).val('');return false; } );
	 });
	 /*
	 $("#AuditLogSearchForm_from").after('<a href="#" id="clearFrom">Clear</a>');
	 $("#clearFrom").click( function(){$("#AuditLogSearchForm_from").val('');return false; } );
	 
	 $("#AuditLogSearchForm_to").after('<a href="#" id="clearTo">Clear</a>');
	 $("#clearTo").click( function(){$("#AuditLogSearchForm_to").val('');return false; } ) ;
	 */

});
</script>
<h2><?php echo $model->modelLabel; ?> Search</h2>

<div class="yiiForm">
<?php
echo $form->render();
?>
</div>

protected/views/auditLog/show.php
<?php
	$this->beginClip('Information');
	$this->renderPartial('/common/show', array('model'=>$model, 'tab'=>'Information'));
	$this->endClip();

	$clips = $this->clips;
	
	$tabs = array (
				'Information'=>array('title'=>'Information', 'content'=>$clips['Information']),
	);
 
	$this->widget('CTabView', array('tabs'=>$tabs, 'viewData'=>array()));
?>

protected/views/auditLog/update.php
<?php echo '<h2>Update ' . $model->tableName() . ' - ' . $model->id . '</h2>'; ?>

<?php echo $this->renderPartial('/common/form', array(
	'model'=>$model,
	'update'=>true,
)); ?>